MMTR-34: close modal by changing pending state
ms1solutionsg0/tcs pull request #12
Opened 2019-03-14 18:54 UTC by ThatDevOpNeal

2019-03-14 19:02 UTC, ThatDevOpNeal commented on client/src/js/view/components/AdminModal.js
> +const onClickAdmin = ( msiAdmin, setMsiAdmin, msiAdminPending, setMsiAdminPending ) => {
Just wanted to put this all on one line, seemed to look cleaner.

2019-03-14 19:52 UTC, jfeng-dev requested changes
reset timeout after typing

2019-03-15 19:03 UTC, j-feng13 commented on client/src/js/view/components/AdminModal.js
> +const setModalTimeout = setMsiAdminPending => {
paren

2019-03-15 19:29 UTC, jfeng-dev approved these changes

2019-03-15 19:29 UTC, merged