Mmtr 52
ms1solutionsg0/tcs pull request #27
Opened 2019-04-15 15:57 UTC by ThatDevOpNeal

2019-04-15 16:17 UTC, j-feng13 commented on client/src/js/view/components/AdminModal.js
> +    element.className = element.className + " modal--remove";
^ classList.add / remove as discussed

2019-04-15 16:30 UTC, j-feng13 commented on client/src/js/view/components/AdminModal.js
> +  done && setTimeout(() => done(), 500);
What's the delay for?

2019-04-15 16:31 UTC, j-feng13 commented on client/src/js/view/components/AdminModal.js
> +          class="modal--close"
looks like a trailing space

2019-04-15 16:31 UTC, j-feng13 commented on client/src/js/view/index.js
> +    element.className = element.className + " refresh-stream--remove";
^ classList

2019-04-15 16:33 UTC, j-feng13 commented on client/src/js/view/index.js
> +    setInterval(() => actions.setMsiStreamRefreshPending(true) && actions.stream.close(), STREAM_REFRESH_TIME);
Use a semicolon instead of &&
`setInterval(() => { actions.setMsiStreamRefreshPending(true); actions.stream.close; }, STREAM_REFRESH_TIME)`

2019-04-15 16:43 UTC, jfeng-dev requested changes
Looks mostly good.
Remove that image.

2019-04-15 19:46 UTC, ThatDevOpNeal commented on client/src/js/view/components/AdminModal.js
> +          class="modal--close"
great eye

2019-04-16 18:37 UTC, jfeng-dev approved these changes

2019-04-16 18:37 UTC, merged